### ISSUE TITLE
Incorrect FOC

### ISSUE THREAD

**Issue by bechhof** [Minki-Kim/Macro-Homework#5]
https://github.com/Minki-Kim/Macro-Homework/blob/8b866aeb5b33a7a69efaf4f2817a9ac5c9fd031e/Wieland_HW3/Minki/Wieland_HW3_Minki.tex#L61

There should be another $Z_t$ here

@Minki-Kim

**Comment by bechhof** [comment]
I think there is the same mistake for the utilization FOC

**Comment by Minki-Kim** [comment]
@bechhof Yep there should be another Z_t there. Utilization FOC looks fine tho.
